# Generated by Django 2.1.2 on 2018-10-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0003_auto_20181009_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagemdecontato',
            old_name='nome',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='mensagemdecontato',
            old_name='mensagem',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='mensagemdecontato',
            old_name='email',
            new_name='estado',
        ),
    ]
