# Generated by Django 2.1.2 on 2018-10-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0004_auto_20181020_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Texto Descrição')),
            ],
            options={
                'verbose_name': 'Denúncia de Notícia',
                'verbose_name_plural': 'Denúncias de Notícias',
            },
        ),
        migrations.RenameField(
            model_name='mensagemdecontato',
            old_name='estado',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='mensagemdecontato',
            old_name='descricao',
            new_name='mensagem',
        ),
        migrations.RenameField(
            model_name='mensagemdecontato',
            old_name='cidade',
            new_name='nome',
        ),
    ]
